# Site settings
title: Stephanie's Profile
email: taylor.stephanie7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end designer learning back-end development.
baseurl: "/project-gh-pages"
url: "http://wheehouseio.github.io"
twitter_username: st1vision
github_username:  1vision
permalink: /blog/:year/:title/


# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
    - index
